import type { DurableStateMachine, StateMachineManager } from "@tsva/core/durable-state-machine";
import type { DurableSet } from "@tsva/core/durable-state";

type SetOp<T> =
  | { t: "add"; v: T }
  | { t: "del"; v: T }
  | { t: "clear" }
  | { t: "load"; values: T[] };

/**
 * Produces a deterministic key for a value so structurally-equal values
 * collide regardless of object identity or property insertion order. Scalars
 * (string/number/boolean) are keyed by their `typeof` tag plus their own
 * string form, so distinct scalars (e.g. the string "1" vs the number 1)
 * never collide with each other. Objects and arrays are keyed by a
 * JSON serialization with object keys sorted recursively, so `{a:1,b:2}` and
 * `{b:2,a:1}` produce the same key -- matching a C# record's field-order
 * -independent, by-value `Equals`.
 */
function structuralKey(value: unknown): string {
  if (value === null) return "null:null";
  const type = typeof value;
  if (type !== "object") return `${type}:${String(value)}`;
  return `object:${JSON.stringify(canonicalize(value))}`;
}

function canonicalize(value: unknown): unknown {
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(canonicalize);
  const sortedKeys = Object.keys(value as Record<string, unknown>).sort();
  const result: Record<string, unknown> = {};
  for (const key of sortedKeys) {
    result[key] = canonicalize((value as Record<string, unknown>)[key]);
  }
  return result;
}

/**
 * A journalled set of values, implemented as a `DurableStateMachine`.
 * Values compare by structural (value) equality: scalars (string/number/
 * boolean) dedup as before, and complex objects/arrays dedup when they are
 * structurally equal (same keys/values, independent of property order) --
 * mirroring a C# record's auto-generated by-value `Equals`. Redundant adds
 * and deletes of absent values are no-ops and journal nothing. Each mutation
 * is appended to the grain's log and then applied to memory.
 */
export class DurableSetImpl<T> implements DurableSet<T>, DurableStateMachine {
  private readonly byKey = new Map<string, T>();

  constructor(
    readonly name: string,
    private readonly manager: StateMachineManager,
  ) {}

  get size(): number {
    return this.byKey.size;
  }

  has(value: T): boolean {
    return this.byKey.has(structuralKey(value));
  }

  values(): IterableIterator<T> {
    return this.byKey.values();
  }

  [Symbol.iterator](): IterableIterator<T> {
    return this.byKey.values();
  }

  async add(value: T): Promise<boolean> {
    if (this.byKey.has(structuralKey(value))) return false;
    // The manager applies the op to memory after a successful append.
    await this.manager.append(this.name, { t: "add", v: value } satisfies SetOp<T>);
    return true;
  }

  async delete(value: T): Promise<boolean> {
    if (!this.byKey.has(structuralKey(value))) return false;
    await this.manager.append(this.name, { t: "del", v: value } satisfies SetOp<T>);
    return true;
  }

  async clear(): Promise<void> {
    await this.manager.append(this.name, { t: "clear" } satisfies SetOp<T>);
  }

  reset(): void {
    this.byKey.clear();
  }

  apply(payload: unknown): void {
    const op = payload as SetOp<T>;
    switch (op.t) {
      case "add":
        this.byKey.set(structuralKey(op.v), op.v);
        break;
      case "del":
        this.byKey.delete(structuralKey(op.v));
        break;
      case "clear":
        this.byKey.clear();
        break;
      case "load":
        this.byKey.clear();
        for (const v of op.values) this.byKey.set(structuralKey(v), v);
        break;
    }
  }

  snapshot(): unknown {
    return { t: "load", values: [...this.byKey.values()] } satisfies SetOp<T>;
  }
}
